name: CI

on:
  schedule:
    - cron: '0 09 * * 1'

  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.0' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script 
        run: |
          git config --local user.email "lelapietra@gmail.com"
          git config --local user.name "LucasLaPietra"
          python webscraper.py
